app = 'vaultwarden-byrdson'
primary_region = 'sin'
kill_signal = 'SIGTERM'
kill_timeout = '2m0s'

[build]
  image = 'vaultwarden/server:1.36.0'

[env]
  DOMAIN = 'https://vaultwarden.byrdsonservices.com'
  SIGNUPS_ALLOWED = 'false'
  SIGNUPS_DOMAINS_WHITELIST = 'byrdsonservices.com'
  SSO_ENABLED = 'true'
  SSO_AUTHORITY = 'https://accounts.google.com'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

[[mounts]]
  source = 'vaultwarden_byrdson_volume'
  destination = '/data'
  auto_extend_size_threshold = 90
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '5GB'
  scheduled_snapshots = false

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 512